# Generated by Django 3.2.10 on 2022-01-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='img', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
